import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Agenda telefônica",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white min-h-screen`}
      >
        {/* NAVBAR */}
        <div className="flex justify-between items-center p-4 border-b border-gray-200 bg-white shadow-sm">

          <div>
            {/* LOGO */}
          <h1 className="text-2xl font-bold text-blue-600">
            Agenda telefônica
          </h1>

          {/* Pequeno texto abaixo da logo*/}
          <p className="text-sm text-gray-500">
            Gerencie seus contatos em um só lugar.
          </p>
          </div>
          
          {/* Botões de Entrar e Cadastrar*/}
          <div className="flex gap-4">
            <button className="font-bold text-gray-700 px-4 py-2 rounded-xl hover:bg-gray-200 cursor-pointer transition shadow-md">Entrar</button>
            <button className="font-bold bg-blue-600 text-white px-4 py-2 rounded-xl hover:bg-blue-500 cursor-pointer transition shadow-md">Cadastrar-se</button>
          </div>
        </div>
        
        {children}
      </body>
    </html>
  );
}
